import { mfSproutTheme } from "./themes/mfSproutTheme.js";

export const PET_ASSET_BASE_URL = "/assets/pet";

export const PET_TEXT = {
    zh: {
        title: "你好，我是苗丰精灵。",
        subtitle: "我可以带你去商城、百科，也可以回答种植问题。",
        toggleLabel: "打开或收起苗丰精灵",
        closeLabel: "收起苗丰精灵面板",
        actions: {
            mall: "进入商城",
            encyclopedia: "查看树木百科",
            ai: "问苗丰精灵",
            merchant: "商家入驻",
        },
        chat: {
            title: "苗丰精灵",
            closeLabel: "收起苗丰精灵对话",
            welcome: "我在这里。你可以问我苗木选择、养护、肥料使用或平台服务相关问题。",
            placeholder: "输入种植、养护或平台问题",
            send: "发送",
        },
        menu: {
            expand: "展开面板",
            collapse: "收起面板",
            chat: "打开聊天",
            dashboard: "任务面板",
            dashboardClose: "关闭任务面板",
            settings: "设置...",
            sessionHudPin: "固定任务条",
            sessionHudUnpin: "取消固定任务条",
            miniEnter: "进入 Mini",
            miniExit: "退出 Mini",
            lowPowerOn: "开启低功耗",
            lowPowerOff: "关闭低功耗",
            doNotDisturbOn: "进入睡眠勿扰",
            doNotDisturbOff: "唤醒精灵",
            permissionBubblesOn: "开启权限气泡",
            permissionBubblesOff: "关闭权限气泡",
            bubblesOn: "恢复所有气泡",
            bubblesOff: "隐藏所有气泡",
            muteOn: "静音",
            muteOff: "取消静音",
            resetPosition: "重置位置",
            hide: "隐藏精灵",
        },
        dashboard: {
            title: "任务面板",
            closeLabel: "关闭任务面板",
            empty: "暂无活跃任务。",
            emptyFiltered: "当前筛选下暂无任务。",
            localGroup: "本地任务",
            filters: {
                all: "全部",
                running: "运行",
                waiting: "等待",
                done: "完成",
            },
            noEvents: "暂无事件",
            renameSession: "重命名任务",
            focusSession: "定位",
            acknowledgeSession: "已读",
            hideSession: "隐藏",
            endSession: "结束",
            agent: "来源",
            model: "模型",
            cwd: "目录",
            host: "主机",
            platform: "系统",
            editor: "编辑器",
            hook: "Hook",
            focusResult: "定位",
            headless: "后台",
            yes: "是",
            updated: "Updated",
            started: "Started",
        },
        sessionHud: {
            otherActive: "{count} other active",
            completionUnread: "Completed. Click to mark as read.",
            elapsed: "Updated",
            focusUnavailable: "Focus unavailable",
        },
        stateLabels: {
            hidden: "隐藏",
            appearing: "出现",
            idle: "待机",
            expanded: "展开",
            thinking: "思考中",
            working: "工作中",
            juggling: "多任务中",
            carrying: "搬运中",
            sweeping: "整理中",
            notification: "通知",
            attention: "提醒",
            success: "积极反馈",
            unclear: "疑惑",
            error: "错误",
            resting: "休息",
            "mini-idle": "极简待机",
            "mini-peek": "探出",
            "mini-alert": "极简通知",
            "mini-happy": "极简开心",
            "mini-working": "极简工作",
            "mini-sleep": "极简休息",
        },
        sessionBadges: {
            running: "运行中",
            waiting: "等待确认",
            done: "已完成",
            blocked: "已阻塞",
            stale: "已过期",
            idle: "空闲",
        },
        contextUsage: {
            label: "上下文",
            tokens: "{used} tokens",
        },
        quotaUsage: {
            label: "额度",
            remaining: "剩余 {remaining}",
            resetIn: "{time} 后重置",
        },
    },
    en: {
        title: "Hi, I am the MF Forest Pet.",
        subtitle: "I can guide you to the mall, encyclopedia, or planting advice.",
        toggleLabel: "Open or collapse the MF Forest Pet",
        closeLabel: "Collapse the MF Forest Pet panel",
        actions: {
            mall: "Enter Mall",
            encyclopedia: "Tree Encyclopedia",
            ai: "Ask MF Pet",
            merchant: "Merchant Entry",
        },
        chat: {
            title: "MF Forest Pet",
            closeLabel: "Collapse the MF Forest Pet chat",
            welcome: "I am here. Ask me about seedlings, care, fertilizer usage, or platform services.",
            placeholder: "Ask about planting, care, or platform services",
            send: "Send",
        },
        menu: {
            expand: "Expand panel",
            collapse: "Collapse panel",
            chat: "Open chat",
            dashboard: "Sessions dashboard",
            dashboardClose: "Close dashboard",
            settings: "Settings...",
            sessionHudPin: "Pin session HUD",
            sessionHudUnpin: "Unpin session HUD",
            miniEnter: "Enter Mini",
            miniExit: "Exit Mini",
            lowPowerOn: "Enable low power",
            lowPowerOff: "Disable low power",
            doNotDisturbOn: "Sleep / Do not disturb",
            doNotDisturbOff: "Wake pet",
            permissionBubblesOn: "Enable permission bubbles",
            permissionBubblesOff: "Disable permission bubbles",
            bubblesOn: "Show all bubbles",
            bubblesOff: "Hide all bubbles",
            muteOn: "Mute",
            muteOff: "Unmute",
            resetPosition: "Reset position",
            hide: "Hide pet",
        },
        dashboard: {
            title: "Sessions",
            closeLabel: "Close sessions dashboard",
            empty: "No active sessions.",
            emptyFiltered: "No sessions in this filter.",
            localGroup: "Local sessions",
            filters: {
                all: "All",
                running: "Running",
                waiting: "Waiting",
                done: "Done",
            },
            noEvents: "No events yet",
            renameSession: "Rename session",
            focusSession: "Focus",
            acknowledgeSession: "Read",
            hideSession: "Hide",
            endSession: "End",
            agent: "Agent",
            model: "Model",
            cwd: "Path",
            host: "Host",
            platform: "Platform",
            editor: "Editor",
            hook: "Hook",
            focusResult: "Focus",
            headless: "Headless",
            yes: "Yes",
            updated: "Updated",
            started: "Started",
        },
        sessionHud: {
            otherActive: "{count} other active",
            completionUnread: "Completed. Click to mark as read.",
            elapsed: "Updated",
            focusUnavailable: "Focus unavailable",
        },
        stateLabels: {
            hidden: "Hidden",
            appearing: "Appearing",
            idle: "Idle",
            expanded: "Expanded",
            thinking: "Thinking",
            working: "Working",
            juggling: "Juggling",
            carrying: "Carrying",
            sweeping: "Sweeping",
            notification: "Notification",
            attention: "Attention",
            success: "Success",
            unclear: "Unclear",
            error: "Error",
            resting: "Resting",
            "mini-idle": "Mini idle",
            "mini-peek": "Mini peek",
            "mini-alert": "Mini alert",
            "mini-happy": "Mini happy",
            "mini-working": "Mini working",
            "mini-sleep": "Mini sleep",
        },
        sessionBadges: {
            running: "Running",
            waiting: "Waiting",
            done: "Done",
            blocked: "Blocked",
            stale: "Stale",
            idle: "Idle",
        },
        contextUsage: {
            label: "Context",
            tokens: "{used} tokens",
        },
        quotaUsage: {
            label: "Quota",
            remaining: "{remaining} left",
            resetIn: "resets in {time}",
        },
    },
};

export const PET_LINKS = {
    mall: "#",
    encyclopedia: "#",
    ai: "#",
    merchant: "#",
};

export const PET_ACTIONS = ["mall", "encyclopedia", "ai", "merchant"];

export const DEFAULT_PET_OPTIONS = {
    theme: mfSproutTheme,
    assetsBaseUrl: PET_ASSET_BASE_URL,
    lang: "zh",
    links: PET_LINKS,
    storageKey: "mf-forest-pet",
    initialState: "idle",
    restore: true,
    initiallyVisible: false,
    initiallyExpanded: false,
};
