// Local prototype theme only. Do not ship Clawd artwork in MF releases.
// Point assetsBaseUrl at clawd-on-desk/assets/svg when running a local demo.
export const clawdDevTheme = {
    schemaVersion: 1,
    id: "clawd-dev",
    name: "Clawd Dev Placeholder",
    version: "0.1.0",
    assetBaseUrl: "../clawd-on-desk/assets/svg",
    canvas: {
        width: 288,
        height: 288,
    },
    states: {
        idle: ["clawd-idle-follow.svg"],
        appearing: ["clawd-mini-enter.svg"],
        expanded: ["clawd-happy.svg"],
        thinking: ["clawd-working-thinking.svg"],
        working: ["clawd-working-typing.svg"],
        juggling: ["clawd-working-juggling.svg"],
        carrying: ["clawd-working-carrying.svg"],
        sweeping: ["clawd-working-sweeping.svg"],
        notification: ["clawd-notification.svg"],
        attention: ["clawd-happy.svg"],
        success: ["clawd-happy.svg"],
        unclear: ["clawd-working-thinking.svg"],
        error: ["clawd-error.svg"],
        resting: ["clawd-sleeping.svg"],
    },
    eyeTracking: {
        enabled: true,
        states: ["idle", "mini-idle", "mini-peek", "mini-working"],
        eyeRatioX: 0.489,
        eyeRatioY: 0.756,
        maxOffset: 3,
        bodyScale: 0.33,
        shadowStretch: 0.15,
        shadowShift: 0.3,
        ids: {
            eyes: "eyes-js",
            body: "body-js",
            shadow: "shadow-js",
        },
    },
    workingTiers: [
        { minSessions: 3, file: "clawd-working-building.svg" },
        { minSessions: 2, file: "clawd-headphones-groove.svg" },
        { minSessions: 1, file: "clawd-working-typing.svg" },
    ],
    jugglingTiers: [
        { minSessions: 2, file: "clawd-working-juggling.svg" },
        { minSessions: 1, file: "clawd-headphones-groove.svg" },
    ],
    displayHintMap: {
        "clawd-building.gif": "clawd-working-building.svg",
        "clawd-typing.gif": "clawd-working-typing.svg",
        "clawd-headphones-groove.gif": "clawd-headphones-groove.svg",
        "clawd-juggling.gif": "clawd-working-juggling.svg",
        "clawd-thinking.gif": "clawd-working-thinking.svg",
        "clawd-idle-reading.gif": "clawd-idle-reading.svg",
        "clawd-bubble.gif": "clawd-idle-bubble.svg",
    },
    idleAnimations: [
        { file: "clawd-idle-reading.svg", duration: 6000 },
        { file: "clawd-idle-bubble.svg", duration: 5000 },
    ],
    reactions: {
        drag: { file: "clawd-react-drag.svg" },
        clickLeft: { file: "clawd-react-annoyed.svg", duration: 2200 },
        clickRight: { file: "clawd-react-double-jump.svg", duration: 2200 },
        double: { files: ["clawd-react-double-jump.svg"], duration: 2600 },
    },
    miniMode: {
        supported: true,
        states: {
            "mini-idle": ["clawd-mini-idle.svg"],
            "mini-enter": ["clawd-mini-enter.svg"],
            "mini-peek": ["clawd-mini-peek.svg"],
            "mini-alert": ["clawd-mini-alert.svg"],
            "mini-happy": ["clawd-mini-happy.svg"],
            "mini-working": ["clawd-mini-typing.svg"],
            "mini-sleep": ["clawd-mini-sleep.svg"],
        },
    },
    timings: {
        minDisplay: {
            appearing: 700,
            notification: 2500,
            attention: 1800,
            working: 1000,
            success: 1800,
            unclear: 1800,
            error: 2500,
        },
        autoReturn: {
            appearing: 700,
            notification: 2800,
            attention: 2200,
            success: 2200,
            unclear: 2600,
            error: 3200,
        },
        restingAfter: 60000,
        idleAnimationAfter: 9000,
    },
    ui: {
        spriteSize: 168,
        panelWidth: 344,
    },
};
